#!/bin/bash
set -evu

# Usage:
#
# build-test [mypy|nomypy]
#
# Arguments:
# - mypy: include mypy check ("mypy" or "nomypy")
#
# Environment variables used:
# - GITHUB_WORKSPACE: workspace directory
#
# WARNING: running this locally will delete any local files that
# aren't strictly part of the git tree, including gitignored files!

MODULE=pytket-custatevec

MYPY=$1

PLAT=`python -c 'import platform; print(platform.system())'`

PYVER=`python -c 'import sys; print(".".join(map(str, sys.version_info[:2])))'`

git clean -dfx

echo "Module to test: ${MODULE}"

MODULEDIR="${GITHUB_WORKSPACE}"
ARTIFACTSDIR=${GITHUB_WORKSPACE}/wheelhouse

rm -rf ${ARTIFACTSDIR} && mkdir ${ARTIFACTSDIR}

python -m pip install --upgrade pip wheel build

# 1. Build the package (sdist and wheel)
python -m build

# 2. Copy the new wheel to your artifacts directory
cp dist/*.whl ${ARTIFACTSDIR}

# Test and mypy:
if [[ "${MYPY}" = "mypy" ]]
then
    python -m pip install "mypy==1.11.2"
fi

# 3. Install your package in editable mode along with all dev/test dependencies.
python -m pip install -e .[dev,test]

# 4. Run pytest from the root, but explicitly point it at the tests directory.
pytest tests/

# 5. Run mypy check if needed
if [[ "${MYPY}" = "mypy" ]]
then
    ${GITHUB_WORKSPACE}/mypy-check ${GITHUB_WORKSPACE}
fi